### ISSUE TITLE
Can I copy “Access Requests” settings to other sites using PnP Provisioning?

### ISSUE THREAD

**Issue by watarufuka** [pnp/PnP-Provisioning-Schema#485]
I am trying to copy a site using PnP Provisioning.

I want to disable "Access Requests" on the destination site.

I tried copy the site with "Access Requests" turned off at the source site.
However, the "Access Requests" setting on the destination site remained on.

Is it possible to copy the setting value of "Access Requests" by the option setting of PnP Provisioning?

![キャプチャ](https://user-images.githubusercontent.com/59820913/74015229-8fefb580-49d3-11ea-99a7-6d24da1a009b.PNG)

**Comment by andersdissing** [comment]
Hey @watarufuka. I just looked in to this. And I did find a way todo it within the template. So, I properly going to create a Provisioning Extensibility
