### ISSUE TITLE
Failure to use provisioning engine params to define property bag overwrite value

### ISSUE THREAD

**Issue by holylander** [pnp/PnP-Provisioning-Schema#487]
Hi there!
I have noticed that, for a given site provisioning .xml template, that contains certain provisioning parameters:
```
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.13.1909.0, Culture=neutral, PublicKeyToken=5e633289e95c321a">
    <pnp:Parameters>
      <pnp:Parameter Key="param_overwrite" />
      <pnp:Parameter Key="param_newvalue" />
    </pnp:Parameters>
  </pnp:Preferences>
```
In case you need/want to use such "param_overwrite" value to define whether certain property bag should be reindexed:
```
<pnp:PropertyBagEntries>        
        <pnp:PropertyBagEntry Key="my_custompropbag" Value="{parameter:param_newvalue}" Overwrite="{parameter:param_overwrite}" Indexed="true" />
</pnp:PropertyBagEntries>
```
Such .xml configuration when return an error when you try to apply it, even if you call the api following a valid example like:

`Apply-PnPProvisioningTemplate -Path $path -Connection $target_con.context -Pârameters @{"param_overwrite" ="true","param_newvalue" =1234 }`

**Comment by PaoloPia** [comment]
The Overwrite attribute does not support parameters, it can only be a boolean (true/false): https://github.com/pnp/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2020-02.xsd#L2680
