### ISSUE TITLE
pnp:App for existing app (An instance of this App already exists at the specified location)

### ISSUE THREAD

**Issue by Rafaelki** [pnp/PnP-Provisioning-Schema#493]
I think issue #433 should be reopened. It looks like @PaoloPia has not read the question before answering.
Basically the request is to avoid the template from failing if the app exits. @jonathanhotono proposes a new action called InstallOrUpdate. Alternatively, a Force parameter could achieve the same result.

**Comment by jonathanhotono** [comment]
Thanks for bringing this up again @Rafaelki . I totally missed that thread. But yes, we definitely need that new action to avoid the template from failing if the app already exists.

**Comment by manoj75** [comment]
Has this been resolved?

**Comment by jonathanhotono** [comment]
This has not been resolved and not sure whether they even seen this.

**Comment by wspelt** [comment]
I'm experiencing the same issue.

The code here looks like it only writes a warning message and skips provisioning if allready installed.
[https://github.com/pnp/PnP-Sites-Core/blob/master/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectApplicationLifecycleManagement.cs](url)

WriteMessage($"App with ID {appId} already exists in the target site and will be skipped", ProvisioningMessageType.Warning);

But instead an error occurs with "app allready exists".
As suggested there needs to be an InstallOrUpdate option or and OverWrite option with Action="Install"

**Comment by jonathanhotono** [comment]
Not sure whether anyone has picked this up.. 
Sorry @VesaJuvonen can this request be considered? We need an option to overwrite/update existing spfx app in `<pnp:Apps>` 
So we can do something like: 
`<pnp:App AppId="{xxx}" Action="**InstallOrUpdate**" />`

**Comment by PaoloPia** [comment]
We're in the process of defining a new version of the Provisioning Schema and we'll consider this suggestion.

Currently, the engine installs a new app, when you specify an Action with value UploadAndPublish or Publish for the Package and an Action with value Install for the App. Moreover, the engine updates an already existing app when you specify an Action with value UploadAndPublish or Publish for the Package and an Action with value Update for the App.

If you ask the engine to Install an app that is already installed, while you should ask for an Update, it will clearly fail. As such, we can consider an additional option "InstallOrUpdate".

**Comment by Rafaelki** [comment]
@PaoloPia thanks for your answer. "InstallOrUpdate" is **LITERALLY** what we asked for. If you spend a bit of time reading the issue and the comments you will see the motive of this request: We want to reapply a template without failing.

**Comment by VesaJuvonen** [comment]
There is a bit of a strange tone on this thread for sure. Please remember that @PaoloPia is using his own time for your benefit for free... he is helping you @Rafaelki as he tries to solve your issue... Using friendlier tone will certainly help people to be more helpful and willing to assist faster on your issues as well.

**Comment by wspelt** [comment]
Good point @VesaJuvonen.
Also @Rafaelki, I believe it is encouraged to submit your own pull request whenever possible, since PnP is essentially an open source community project adeopted by Microsoft if I'm correct.
@PaoloPia thanks for considering the suggestions in this thread.

**Comment by Rafaelki** [comment]
@wspelt this is a change in the schema, so I don't think it is something that can be modified for everybody.

**Comment by wspelt** [comment]
@Rafaelki agree: I would not know where to start myself actually :).

**Comment by PaoloPia** [comment]
Clearly, updating the schema requires proper design and quite some time and effort. We used to release a new schema every 4-6 months, collecting all the community requests and adding support for the new functionalities released by Microsoft. However, in 2020, due to numerous reasons, we released just the Feb 2020 schema. Now I've added the requested option to the March 2021 schema. After sealing the schema, we'll need to update the actual implementation in PnP Framework (PnP Sites Core is now archived) and then the new functionality will be out. I'm going to close this item because, from a PnP Provisioning Schema point of view, it is now managed. I'll create a new issue in PnP Framework, once the schema will be updated there. At that point in time, feel free to pick up the item and implement it, or you can simply keep on updating the Action property in the template from Install to Update, after the first installation, while waiting for someone to implement the new option.

**Comment by wspelt** [comment]
For anyone needing a quick fix for this in the meanwhile you could use this code "as is" in addition to the template:

```
public static void InstallSingleApp(ClientContext context, Guid appId, string appTitle)
{
	AppManager manager = new AppManager(context);

	// Get the apps already installed in the site
	var siteApps = manager.GetAvailable()?.Where(a => a.InstalledVersion != null)?.ToList();
	// Check on the title, installed id is different than package-solution id
	var alreadyExists = siteApps.Any(a => a.Title == appTitle);

	if (alreadyExists)
	{
		Log.Write($"App '{appTitle}' is already installed. Skipping installation.");
		return;
	}

	try
	{
		Log.Write($"Installing app '{appTitle}'.");

		Task installTask = Task.Run(async () => await manager.InstallAsync(appId));
		installTask.Wait();

		Log.Write($"App '{appTitle}' installed.");

	}
	catch (Exception ex)
	{
		Log.Write(TraceEventType.Error, "Exception Caught - Mostly because the App is already installed. Skipping Install. Message - " + ex.InnerException.Message);
	}
}
```
