### ISSUE TITLE
Error deploying new site provisioning to GCC-H tenant

### ISSUE THREAD

**Issue by robgarrett** [pnp/PnP-Provisioning-Schema#501]
https://lookbook.microsoft.com uses the SharePoint PnP Provisioning engine to deploy new sites to SharePoint Online. Unfortunately, it gives an error on a GCC-H tenant (error attached).
![error](https://user-images.githubusercontent.com/5890182/78571997-e5d6b300-77f4-11ea-85df-c2e2cd987c73.png)

**Comment by robgarrett** [comment]
Realted? https://github.com/pnp/custom-learning-office-365/issues/199

**Comment by PaoloPia** [comment]
GCC tenants should now be supported. Please, download the latest release of the engine and try again.
