### ISSUE TITLE
Update request: add Name and Remove attributes for Document Sets

### ISSUE THREAD

**Issue by KoenZomers** [pnp/PnP-Provisioning-Schema#502]
Please add the optional attributes Name of type xsd:string and Remove of type xsd:bool to:

- ContentType\DocumentSetTemplate\AllowedContentTypes\AllowedContentType
- ContentType\DocumentSetTemplate\SharedFields\SharedField
- ContentType\DocumentSetTemplate\WelcomePageFields\WelcomePageField

Sample updated XML template which makes use of these attributes would look like:

```xml
        <pnp:ContentType ID="0x0120D52000633285944A99674FAFB784B02F6BAF10" Name="Custom Docset" Description="" Group="Custom Content Types" NewFormUrl="_layouts/15/NewDocSet.aspx" EditFormUrl="" DisplayFormUrl="">
          <pnp:FieldRefs>
            <pnp:FieldRef ID="b234d423-1f9a-47a9-a9da-7d7811578b5d" Name="PnP_x0020_Rocks" UpdateChildren="true" />
          </pnp:FieldRefs>		
          <pnp:DocumentSetTemplate>
            <pnp:AllowedContentTypes>
              <pnp:AllowedContentType Name="test" ContentTypeID="0x0101" Remove="false" />
            </pnp:AllowedContentTypes>
            <pnp:SharedFields>
              <pnp:SharedField ID="cbb92da4-fd46-4c7d-af6c-3128c2a5576e" Name="DocumentSetDescription" Remove="false" />
              <pnp:SharedField ID="01af4761-a672-40b6-9148-f39150490e7e" Name="Another_x0020_field" Remove="true" />
            </pnp:SharedFields>
            <pnp:WelcomePageFields>
                <pnp:WelcomePageField Remove="false" ID="437fb870-cc28-40eb-8498-2a108c580e53" Name="Second_x0020_column" />
		<pnp:WelcomePageField Remove="true" ID="01af4761-a672-40b6-9148-f39150490e7e" Name="Another_x0020_field" />
		<pnp:WelcomePageField ID="b234d423-1f9a-47a9-a9da-7d7811578b5d" Name="PnP_x0020_Rocks" />
            </pnp:WelcomePageFields>
          </pnp:DocumentSetTemplate>
        </pnp:ContentType>
```
PR that will work with these new attributes has been submitted here: https://github.com/pnp/PnP-Sites-Core/pull/2624

The PR contains the requested schema changes already in the current latest schema, so these would need to be transferred to the new to be created schema:
https://github.com/pnp/PnP-Sites-Core/pull/2624/files#diff-8eef80de0298b0821deb0423cf9b4528

**Comment by PaoloPia** [comment]
These changes are now defined in schema version 202103 and when the schema will be sealed and included in PnP Framework, we will be more than happy to see a PR to implement the corresponding provisioning behavior. Thanks.

**Comment by KoenZomers** [comment]
Thanks @PaoloPia. I'll see if I can find time to port the PR for the actual implementation to the current code. I remember it took me 4 days to build it all :)
