### ISSUE TITLE
Make Team Visibility Configurable with Parameters

### ISSUE THREAD

**Issue by mirkori** [pnp/PnP-Provisioning-Schema#507]
For <pnp:Team> We can pass "GroupId", "DisplayName", "Description" values without issues.

We can not pass "Visibility" parameter because it cannot parse the String value coming from the Parameter as enum.

**Comment by PaoloPia** [comment]
Hi,
The Visibility attribute does not support tokens (https://github.com/pnp/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2020-02.xsd#L8234). I'm sorry.
