### ISSUE TITLE
Duplicate site collection menu items when using PnP-Provisioning

### ISSUE THREAD

**Issue by aelfyano** [pnp/PnP-Provisioning-Schema#516]
I've used Get and Apply-PnPProvisioningTemplate commands for a couple times already where navigation items (top bar for Communication sites) are duplicated.

In the example below, Home results into 2 entries after creating a new site. Should I just remove items under pnp:NavigationNode when the XML file is generated? 

        <pnp:CurrentNavigation NavigationType="StructuralLocal">
          <pnp:StructuralNavigation RemoveExistingNodes="false">
            <pnp:NavigationNode Title="Home" Url="{site}" />
          </pnp:StructuralNavigation>
        </pnp:CurrentNavigation>

Thanks! 
@fredyano

**Comment by PaoloPia** [comment]
Hi, it is a known behavior. You should specify RemoveExistingNodes="true" in order to reset the menu items when you provision.
