### ISSUE TITLE
Question : can I set the "HiddenFromExchangeClientsEnabled" of a group using Provisioning/Tenant/Office365GroupSettings ?

### ISSUE THREAD

**Issue by JMTeamway** [pnp/PnP-Provisioning-Schema#521]
Hi all !

First I am sorry if it is not the right place to ask a question, any advise welcome on the correct place !

I would like for a new Team site to perform the equivalent of the powershell command using Pnp provisionning  :
`set-UnifiedGroup -identity $GroupName -HiddenFromExchangeClientsEnabled:$false`

I tried the following Schema that was applied without issue during some tests, but did not performed what I expected/hoped :
```
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2019/03/ProvisioningSchema">
	<pnp:Tenant>
		<pnp:Office365GroupsSettings>
			<pnp:Property Key="HiddenFromExchangeClientsEnabled" Value="false" />
		</pnp:Office365GroupsSettings>
	</pnp:Tenant>
</pnp:Provisioning>
```

Is it possible to do it by using <pnp:Office365GroupsSettings> ?
If not, is there any other mean to do so using provisionning ?
And after all, what deployment scenario / configuration / exotic trick could we imagine to automatically have this setting set each Teams creation ? 

Thanks all for your help !

**Comment by PaoloPia** [comment]
We'll consider this requirement for the next version of the PnP Provisioning Schema. Thanks.

**Comment by PaoloPia** [comment]
I've just added the attribute to the next schema version, as such I'm going to close this item.
