### ISSUE TITLE
Provisioning page with list or document library webpart fails

### ISSUE THREAD

**Issue by Leif-Frederiksen** [pnp/PnP-Provisioning-Schema#524]
When I use Apply-PnPProvisioningTemplate, the standard webparts for document library and list no longer gets installed on the page. Other webparts work fine.
This behaviour seems to have begin very recently - last couple of days.
To reproduce:

1. Create a page with just a document library webpart.
2. Set the page to be the websites start page.
3. Connect to the site: Connect-PnPOnline -Url https://...
4. Get the template: Get-PnPProvisioningTemplate -Out c:\temp\page.xml -Handlers PageContents
5. Apply the same template the site: Apply-PnPProvisioningTemplate -Path C:\temp\page.xml

The page is now just a blank page - without the document library webpart. Same thing happens for list webparts, but for example text webparts work fine.

If I look into the trace log (Set-PnPTraceLog -On -Level Debug) I get this error message: Could not find the control with either ID = f92bf067-bc19-489e-a556-7fe95f508
720 or Name =  to install. Did you install your client side web part to this site?

It is a standard out-of-the-box webpart, so I have not "installed it".

If am running version 3.25.2009.1 of PnP Powershell.

The contents of the template is this: 
```
<?xml version="1.0"?>
<pnp:Provisioning xmlns:pnp="http://schemas.dev.office.com/PnP/2020/02/ProvisioningSchema">
  <pnp:Preferences Generator="OfficeDevPnP.Core, Version=3.25.2009.1, Culture=neutral, PublicKeyToken=5e633289e95c321a" />
  <pnp:Templates ID="CONTAINER-TEMPLATE-0584A4AAAE374171AB9A224A4435A375">
    <pnp:ProvisioningTemplate ID="TEMPLATE-0584A4AAAE374171AB9A224A4435A375" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:WebSettings NoCrawl="false" WelcomePage="SitePages/LFR.aspx" CommentsOnSitePagesDisabled="false" QuickLaunchEnabled="false" SearchScope="DefaultScope" SearchBoxInNavBar="Inherit" />
      <pnp:ClientSidePages>
        <pnp:ClientSidePage PromoteAsNewsArticle="false" PromoteAsTemplate="false" Overwrite="true" EnableComments="false" Title="LFR" ThumbnailUrl="" PageName="LFR.aspx">
          <pnp:Header Type="Custom" ServerRelativeImageUrl="/_LAYOUTS/IMAGES/SLEEKTEMPLATEIMAGETILE.JPG" LayoutType="NoImage" TextAlignment="Center" ShowTopicHeader="false" ShowPublishDate="false" TopicHeader="" AlternativeText="" Authors="[&#xD;&#xA;  {&#xD;&#xA;    &quot;id&quot;: &quot;i:0#.f|membership|lfr@mth.dk&quot;,&#xD;&#xA;    &quot;upn&quot;: &quot;lfr@mth.dk&quot;,&#xD;&#xA;    &quot;email&quot;: &quot;lfr@mth.dk&quot;,&#xD;&#xA;    &quot;name&quot;: &quot;Leif Frederiksen&quot;,&#xD;&#xA;    &quot;role&quot;: &quot;IT-udvikler, SharePoint&quot;&#xD;&#xA;  }&#xD;&#xA;]" AuthorByLine="[&#xD;&#xA;  &quot;i:0#.f|membership|lfr@mth.dk&quot;&#xD;&#xA;]" AuthorByLineId="-1" />
          <pnp:Sections>
            <pnp:Section Order="1" Type="OneColumn">
              <pnp:Controls>
                <pnp:CanvasControl WebPartType="List" JsonControlData="{&quot;id&quot;: &quot;f92bf067-bc19-489e-a556-7fe95f508720&quot;, &quot;instanceId&quot;: &quot;93c78a74-ca09-48dd-962c-a00bb5e8c9a4&quot;, &quot;n&quot;: &quot;Dokumentbibliotek&quot;, &quot;description&quot;: &quot;Tilføj et dokumentbibliotek&quot;, &quot;dataVersion&quot;: &quot;1.0&quot;, &quot;properties&quot;: {&quot;isDocumentLibrary&quot;:true,&quot;filterBy&quot;:{}}, &quot;serverProcessedContent&quot;: {}, &quot;dynamicDataPaths&quot;: {}, &quot;dynamicDataValues&quot;: {}}" ControlId="f92bf067-bc19-489e-a556-7fe95f508720" Order="1" Column="1" />
              </pnp:Controls>
            </pnp:Section>
          </pnp:Sections>
        </pnp:ClientSidePage>
      </pnp:ClientSidePages>
    </pnp:ProvisioningTemplate>
  </pnp:Templates>
</pnp:Provisioning>

```

**Comment by BeetLuke** [comment]
Same here. In a daily provisioning task I notice this appearing just this morning 1am CET. 
Update of PnP PowerShell does not help.

Assuming something changed on the IDs or Configuration on the SharePoint Side I extracted a newly created SitePage and applied the PnP-Template which showed the same behaviour.

I don't see the List WebPart in Get-PnPAvailableClientSideComponents. But I don't know if it ever appeared in this command.

**Comment by joelfmrodrigues** [comment]
Same here, missing list web part from page

**Comment by joelfmrodrigues** [comment]
Update: https://twitter.com/LukusMuller/status/1311286890151149569

**Comment by joelfmrodrigues** [comment]
Just tested and can confirm that it is now working at my end.

**Comment by Leif-Frederiksen** [comment]
I can also confirm that this is working again - thank  you for looking into this :-)
