### ISSUE TITLE
pnp:Security

### ISSUE THREAD

**Issue by sympmarc** [pnp/PnP-Provisioning-Schema#526]
I'm trying to add an additional user to the members group in my template, as shown in the [AdditionalMembers](https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2020-02.md#security) element in the schema.

I've tried every variation on this that I can come up with, but always get the dreaded `Apply-PnPProvisioningTemplate : Template is not valid`.

What am I missing?

``` xml
    <pnp:ProvisioningTemplate ID="TEMPLATE-3665E7242C1141B0BF1A07D645A8E4DB" Version="1" BaseSiteTemplate="GROUP#0" Scope="RootSite">
      <pnp:WebSettings RequestAccessEmail="" NoCrawl="false" WelcomePage="SitePages/Home.aspx" SiteLogo="" AlternateCSS="" HubSiteUrl="" CommentsOnSitePagesDisabled="false" QuickLaunchEnabled="true" MembersCanShare="true" SearchScope="DefaultScope" SearchBoxInNavBar="Inherit" />
      <pnp:Security>
        <pnp:AdditionalMembers>
          <pnp:UsersList>
            <pnp:User Name="marc@foo.com"></pnp:User>
          </pnp:UsersList>
        </pnp:AdditionalMembers>
      </pnp:Security>
    </pnp:ProvisioningTemplate>
```

**Comment by sympmarc** [comment]
Contrary to the schema docs, this seems to work. I'm not sure what pnp:UserList is supposed to do at this point.
``` xml
      <pnp:Security>
        <pnp:AdditionalMembers>
            <pnp:User Name="marc@foo.com"></pnp:User>
        </pnp:AdditionalMembers>
      </pnp:Security>
```

**Comment by PaoloPia** [comment]
Hi @sympmarc,
The AdditionalMembers element is of type pnp:UsersList (https://github.com/pnp/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2020-02.xsd#L2286), which is made of a sequence of User objects (https://github.com/pnp/PnP-Provisioning-Schema/blob/master/OfficeDevPnP.ProvisioningSchema/ProvisioningSchema-2020-02.xsd#L2730). So the behavior that you see is correct.
