### ISSUE TITLE
Cannot remove Wiki Tab from Teams and some parts of Teams will be applied more than once (when applying twice).

### ISSUE THREAD

**Issue by FeCo22** [pnp/PnP-Provisioning-Schema#528]
Hi,

I have the following errors since about 15.10.2020, before that everything worked fine (no changes to PnPPowerShell version and PnPTenantTemplate Schema):

- When I apply a PnPTenantTemplate and I want to remove a Wiki Tab in Teams, the provisioning do not remove the Wiki tab and stops at that point (additional steps to Teams, for example add channels/tabs won't be run). I get no error message, it just stops.

Applying a sample PnPTenantTemplate
![image](https://user-images.githubusercontent.com/57482499/97287957-7df5c180-1845-11eb-8c96-952fdd640346.png)

Result:
Wiki won't be removed and additional tabs and Message won't be created/posted:
![image](https://user-images.githubusercontent.com/57482499/97287235-a0d3a600-1844-11eb-91cd-9053c2b1bf8e.png)

Result without removing Wiki Tab in PnPTenantTemplate Schema:
![image](https://user-images.githubusercontent.com/57482499/97287808-50107d00-1845-11eb-8ef6-1fa8129320c3.png)

- When I apply a PnPTenantTemplate more than once (two times), some parts of teams will be run twice. It doesn't just apply the Delta. Before just the Delta was applied. For example: If I add a tab to a channel, the tab will be added twice.

Applying a sample PnPTenantTemplate twice: 
![image](https://user-images.githubusercontent.com/57482499/97287925-746c5980-1845-11eb-9018-f345b51f8021.png)

Result:
![image](https://user-images.githubusercontent.com/57482499/97288077-a1b90780-1845-11eb-9953-fd5034d2d7f0.png)

I tested the two above mentioned errors in different Tenants, same behaviour for all tenants.

SharePointPnPPowershellOnline Version: 3.25.2009.1

PnPTenantTemplate Schema (Teams):
![image](https://user-images.githubusercontent.com/57482499/97288867-bba71a00-1846-11eb-9029-3e1efaa717ae.png)

Thank you

**Comment by PaoloPia** [comment]
This issue should have been fixed. Please, upgrade to PnP Framework and PnP PowerShell for PowerShell Core and try again. In case of any further issue, please create issue items in the corresponding repositories and not in this one, which is about the provisioning schema. Thanks.
