### ISSUE TITLE
More examples about provisioning

### ISSUE THREAD

**Issue by brittanyru** [pnp/PnP-Provisioning-Schema#531]
I spent few hours trying to make the provisioning template works, most of the examples aren't for the "sequence" part where you can provision sites, and the ones provided focus on Teams.

I would like to create new communication sites using the templates, however whenever I do:

connect-pnponline "mysite"

and then apply-provisioningtemplate .. it is applied to the site I connected to in the first step, it's not applied to the site I am having in my provisioning template. Are there any examples and tutorials on how to create new sites? I saw the samples in the provisioning engine, but they all show the .xml nothing shows what I need to do from the Powershell side of things. Is it correct to use connect-pnponline [anysite] ?

thanks.

**Comment by PaoloPia** [comment]
Please, take a look at this sample (https://github.com/SharePoint/sp-dev-provisioning-templates/blob/master/tenant/flysafeconference/source/template.xml) and use the https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/invoke-pnptenanttemplate?view=sharepoint-ps command let after connecting with Connect-PnPOnline using a tenant admin account.
