### ISSUE TITLE
Client Side Page - Collapsible sections support in Schema

### ISSUE THREAD

**Issue by czullu** [pnp/PnP-Provisioning-Schema#561]
It would be nice to have the [CanvasSection](https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2021-03.md#canvassection) extended to store Metadata of Collapsible Section as from here [pnpcore-ICanvasSection](https://github.com/pnp/pnpcore/blob/688d1fa4bf3ee960513f1eca9f9300dcdcd053da/src/sdk/PnP.Core/Model/SharePoint/Pages/Public/ICanvasSection.cs).

        /// <summary>
        /// Is this section collapsible?
        /// </summary>
        bool Collapsible { get; set; }

        /// <summary>
        /// Is the collapsible section expanded?
        /// </summary>
        bool IsExpanded { get; set; }

        /// <summary>
        /// DisplayName of the collapsible section
        /// </summary>
        string DisplayName { get; set; }

        /// <summary>
        /// Sets the alignment of the collaps icon, left/right or not configured
        /// </summary>
        IconAlignment? IconAlignment { get; set; }

        /// <summary>
        /// Show a devided line for this collapsible section?
        /// </summary>
        bool ShowDividerLine { get; set; }

**Comment by PaoloPia** [comment]
Hi, thanks for the suggestion. We're working on it.
