### ISSUE TITLE
Teams Channel - ModerationSettings Support

### ISSUE THREAD

**Issue by czullu** [pnp/PnP-Provisioning-Schema#562]
It would be nice to have [teamchannel](https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2021-03.md#teamchannel) schema extended in order to store Teams Channel Moderation Settings as defined here [channelmoderationsettings](https://docs.microsoft.com/en-us/graph/api/resources/channelmoderationsettings?view=graph-rest-beta)

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. The option is now implemented in the next version of the provisioning schema,
