### ISSUE TITLE
Modern Document Library View Mode

### ISSUE THREAD

**Issue by sflvbm454** [pnp/PnP-Provisioning-Schema#568]
Hi,
I've to set the default view mode of an Asset Doc Lib to "COMPACTLIST".
Via Powershell i can do this by setting the attribute ViewType2..

Set-PnPView -List “LIST_NAME” -Identity “VIEW_ID” -Values @{“ViewType2” = “COMPACTLIST”}
Set-PnPView -List “LIST_NAME” -Identity “VIEW_ID” -Values @{“ViewType2” = “TILES”}

There is a way to accomplish this with the provisioning Schema?

Thanks

**Comment by ReidarHusmo** [comment]
Yes.
Add the ViewType2 element to your view definition.
Example: <View...<ViewType2>TILES</ViewType2></View>
