### ISSUE TITLE
Collapsible section not present in extracted site template 

### ISSUE THREAD

**Issue by meklulose** [pnp/PnP-Provisioning-Schema#575]
I have site page that contains collapsible sections. I am using PnP Powershell 1.8.0 and using command `Get-PnPSiteTemplate -Out C:\template.xml -IncludeAllClientSidePages` but the xml doesn't have any reference to section being a collapsible section. It just has 
`<pnp:Sections>`
`<pnp:Section Order="1" Type="OneColumn">`

so when I apply the template the site pages doesn't have collapsible sections in it. 

Is there a solution to this?

**Comment by MarcoSimon** [comment]
I'm running into the same problem (using PnP.PowerShell 1.6.0): when getting the template from a page with collapsible sections, they won't show up in the XML, just their content. So it is not possible to provision a SiteDesign with these sections from template!

It would be nice if there was some reaction on this problem…

**Comment by MarcoSimon** [comment]
I have just updated to PnP.PowerShell 1.9.0, but it still doesn't work.

**Comment by PaoloPia** [comment]
We're working on it at schema level. Thanks.

**Comment by ChrispyBites** [comment]
Hey, @PaoloPia, you closed this last August but the problem still exists as of 1/26/2023.  There's no indication that this has been fixed.  Can we get an ETA on that?

**Comment by PaoloPia** [comment]
Collapsible sections are actually implemented in the schema and in the engine since October 2022.

**Comment by ChrispyBites** [comment]
When I pull templates from my sharepoint sites with pages that include
collapsible sections, collapsible sections are not respected.  If you can
point me in documentation where the schema is identifying a collapsible
section, that'd be great.

**Comment by PaoloPia** [comment]
Here you can see an example: https://github.com/pnp/PnP-Provisioning-Schema/blob/master/Samples/ProvisioningSchema-2022-09-FullSample-01.xml#L1026 - Are you using the latest release of the engine?

**Comment by ChrispyBites** [comment]
I have 1.12, but I'm not taking nightlies.  So, I've seen this guy, and
adding the prop in manually does create a collapsible section, but
export-pnppage doesn't seem to be capturing sections as collapsible when we
try and pull a template off of pre-existing page.

**Comment by Nerloras** [comment]
I'm running version 2.2.0 and I'm still having this problem.

**Comment by ohaak2** [comment]
@Nerloras  Same for me. Also working with 2.2.0. XML schema is  V202209. 

@PaoloPia  If this issue was closed last August and it really was fixed at that time it defintely seems to be broken now (again). I neither get the correct section type nor the section label in my page exports.

**Comment by DeLuca-Marco** [comment]
I am having the same issue, working with 2.2.0.

**Comment by yellowarrownl** [comment]
Glad to hear I'm not the only one. @PaoloPia  is there any update on this issue? My department can't continue with provisioning until this issue is resolved.

**Comment by stevensarginson** [comment]
Are you guys ignoring this, or is it ever going to be fixed?

**Comment by marcoschmucker** [comment]
I use Collapsible sections today but there are still not present in site template using Pnp v 1.12.0

**Comment by marcoschmucker** [comment]
I use Collapsible sections not present in extracted site template

**Comment by ChrispyBites** [comment]
I'm gonna be honest, you guys make it really, really hard to be a partner.

**Comment by MounirMrabet** [comment]
the only workarround that I found is to set all these properties:
$Template = Get-PnPClientSidePage "template.aspx"
$Template.Sections[1].Collapsible = $true
$Template.Sections[1].DisplayName = "Documents"
$Template.Sections[1].IsExpanded = $true
$Template.Sections[1].SectionType = 1
$Template.Sections[1].IconAlignment = "Left"
you can after that save the template.

**Comment by marcoschmucker** [comment]
@MounirMrabet great, thank you very much. That worked for me. Solved my problems. @PaoloPia maybe you can check that?

**Comment by stevensarginson** [comment]
@MounirMrabet Thank you. I had tried something like this but I had missed the IconAlignment which caused it to fail.

You can also directly edit the XML template

`<pnp:Section Order="1" Type="OneColumn" Collapsible="true" DisplayName="Some Name" IsExpanded="false" IconAlignment="Left">
`
