### ISSUE TITLE
Suggestion: Enable Audience Targeting on libraries

### ISSUE THREAD

**Issue by rlv-dan** [pnp/PnP-Provisioning-Schema#576]
It does not seem to be implemented yet.

/_layouts/15/ListEnableTargeting.aspx

**Comment by PaoloPia** [comment]
It means adding support for:
- Enable audience targeting
- Enable classic audience targeting

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. The option is now implemented in the next version of the provisioning schema,
