### ISSUE TITLE
Should the Link Point to PnP Framework instead of PnP Sites Core?

### ISSUE THREAD

**Issue by shurick81** [pnp/PnP-Provisioning-Schema#579]
Currently the link in readme points to the old code:

https://github.com/pnp/PnP-Provisioning-Schema/blob/feffe96525e723d14bbdcd36177771f42c3529aa/README.md?plain=1#L10

**Comment by PaoloPia** [comment]
Hi,
Thanks for creating this issue. It is now fixed in the experimental branch and will become available soon in the main branch.
