### ISSUE TITLE
The ContentTypeID element in the schema should not be validated with pattern

### ISSUE THREAD

**Issue by eduardpaul** [pnp/PnP-Provisioning-Schema#585]
Hi all, using the following provisioning schema we are getting a validation error: 

**Use case:** Add existing content type to list by name using `{contenttypeid:MyContentType}` helper. 

**Error:** 
```PnP.Framework: Template is not valid. One or more errors occurred. (The 'ContentTypeID' attribute is invalid - The value '{contenttypeid:Documento}' is invalid according to its datatype 'http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema:ContentTypeId' - The Pattern constraint failed.) (The 'ContentTypeID' attribute is invalid - The value '{contenttypeid:Documento}' is invalid according to its datatype 'http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema:ContentTypeId' - The Pattern constraint failed.). The 'ContentTypeID' attribute is invalid - The value '{contenttypeid:Documento}' is invalid according to its datatype 'http://schemas.dev.office.com/PnP/2021/03/ProvisioningSchema:ContentTypeId' - The Pattern constraint failed. The Pattern constraint failed.```

**Template:** 
```
<pnp:ListInstance Title="HR Collateral" ...>
          <pnp:ContentTypeBindings>
            <pnp:ContentTypeBinding ContentTypeID="{contenttypeid:Documento}" />
          </pnp:ContentTypeBindings>

```

So, from my point of view this pattern should be removed: 
![image](https://user-images.githubusercontent.com/1370426/161779166-3aae0d08-8236-4770-a49d-e3beaa3817ce.png)

Greetings,

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. I updated the regex to:

(0x[a-zA-Z0-9]+)|(\{.*:.*\})

so that dynamic properties will be supported. The change is now implemented in the next version of the provisioning schema,
