### ISSUE TITLE
Cannot define "ShowBackgroundGradient" in pnp:header

### ISSUE THREAD

**Issue by mhazebroucq** [pnp/PnP-Provisioning-Schema#588]
Hi All

Does anyone know how to define the ShowBackgroundGradient property when provisioning a clientside page ?
This property is not present in the [ProvisioningSchema-2021-03](https://github.com/pnp/PnP-Provisioning-Schema/blob/master/ProvisioningSchema-2021-03.md#header)

Regards

**Comment by PaoloPia** [comment]
Hi, thanks for your feedback. The option is now implemented in the next version of the provisioning schema,

**Comment by mhazebroucq** [comment]
Grate news 😀
Thanks @PaoloPia
