### ISSUE TITLE
Create Shared Channels in Teams

### ISSUE THREAD

**Issue by McoreD** [pnp/PnP-Provisioning-Schema#591]
Hey guys,

We have automated creation of Standard and Private Channels using the templates below:

```
   <pnp:Channels>
        <!-- Standard Channels -->
        <pnp:Channel DisplayName="Communications"
          Description=""
          IsFavoriteByDefault="false" />
       <pnp:Channel DisplayName="Develop"
          Description=""
          IsFavoriteByDefault="false" />
        <pnp:Channel DisplayName="Meetings"
          Description=""
          IsFavoriteByDefault="false" />
        <pnp:Channel DisplayName="Program"
          Description=""
          IsFavoriteByDefault="false" />

        <!-- Private Channels -->
        <pnp:Channel DisplayName="Commercial"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Contract"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Procurement"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
        <pnp:Channel DisplayName="Evaluation"
          Description=""
          IsFavoriteByDefault="false"
          Private="true" />
      </pnp:Channels>
```

Similary, how could you create Shared Channels please? I tried to look for examples everywhere, but could not land on a valid one. 

Thanks,
Michael

**Comment by PaoloPia** [comment]
Hi, Thanks for your feedback. We're going to introduce support for shared channels in the next release of the provisioning schema and engine.

**Comment by McoreD** [comment]
Hi @PaoloPia, this is excellent news. Thanks for taking your time to respond to me. We are developing a PowerShell script to automate Team creation in our corporation. Are you able to provide any indicative time as to when - next year? by end of this year etc.? Noting the last update was March 2021, I am wary that it could be in some time. Thanks.

**Comment by McoreD** [comment]
Hi @PaoloPia just checking if you saw my post above :)

**Comment by McoreD** [comment]
Hi @PaoloPia ,

Thanks for adding Shared Channels support. We are trying to automate the following:

![image](https://user-images.githubusercontent.com/48652/235560440-d0aa4cfe-ab88-4cec-8413-080427620ec7.png)

To implement the effect of the checkBox in the screenshot, would the Private boolean work?

```
       <pnp:Channel DisplayName="Develop"
                    Description=""
                    IsFavoriteByDefault="true"
                    MembershipType="Shared" 
                    Private="true" />

```
Thanks.

**Comment by McoreD** [comment]
@PaoloPia it looks like `MembershipType="Shared"` is the only thing supported. `Private="true"` is not supported. 
We need the following checkBox automated:
![image](https://github.com/pnp/PnP-Provisioning-Schema/assets/48652/a129a1d7-f07b-45ee-801e-baf7b9d6fb5a)
I look forward to receiving your advice.
