### ISSUE TITLE
Feature request: Enable NoScriptSite in provisioning schema

### ISSUE THREAD

**Issue by Laskewitz** [pnp/PnP-Provisioning-Schema#592]
I would love to be able to create a site collection in a PnP Provisioning Template and set a property to make sure NoScriptSite is set to false, so I can fill the property bag, etc. 

Could this be added in the new schema?

**Comment by Laskewitz** [comment]
+ @PaoloPia for awareness 🙂

**Comment by jansenbe** [comment]
@Laskewitz : NoScript is turned on for a reason (security) and making it easy to turn off is not in line with how SharePoint Online works. It's a bit unfortunate that writing to the property bag depends on this as there are no security implications for using the property bag. If you want to store web level property data, you can always use the property bag of a (hidden) list or alternatively add key/value pairs in a hidden list in the web.

The ideal approach would be to have a REST/Graph API that allows CRUD operations on property bags, regardless of the noscript setting. Unfortunately, that's not something we have today but if there's enough customer/community demand it might get added to the backlog.

**Comment by Laskewitz** [comment]
@jansenbe Makes sense (the security reasoning that is), but it would be so much nicer to have one template to rule them all. Now it's a bit cumbersome...

**Comment by PaoloPia** [comment]
After the above discussion, I'll close this item. Thanks everyone.
